services:
  fastapi-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - "8000:8000"

  streamlit-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - BASE_URL=http://fastapi-server:8000
    depends_on:
      - fastapi-server
