services:
  fastapi-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/backend

  streamlit-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/usr/frontend
    env_file:
      - "./frontend/.env"
    depends_on:
      - fastapi-server
